// Pure, side-effect-free core of the extension: endpoint resolution, provider config assembly,
// and balance-response interpretation. Kept separate from index.ts (the wiring) so every branch
// is unit-testable without a live pi runtime or a network call.
import type { ProviderConfig, ProviderModelConfig } from "@earendil-works/pi-coding-agent";

// The env var holding the raw nullsink bearer key ("0sink_..."). Referenced by the provider configs
// as "$NULLSINK_API_KEY" (pi interpolates it at request time) and read directly by the /nullsink
// balance command (which needs the raw value to call GET /balance).
export const API_KEY_ENV = "NULLSINK_API_KEY";

// Optional override for self-hosted / forked deployments. Unset => the public instance.
export const BASE_URL_ENV = "NULLSINK_BASE_URL";

// The public instance. A self-host sets NULLSINK_BASE_URL to its own origin.
export const NULLSINK_DEFAULT_BASE_URL = "https://nullsink.is";

// The provider registration keys. Three providers because nullsink speaks two wire formats and
// groups models into trust tiers; splitting them mirrors the /models page and keeps the /model
// picker legible.
export const PROVIDER_IDS = {
  anthropic: "nullsink",
  openai: "nullsink-openai",
  tinfoil: "nullsink-tinfoil",
} as const;

export interface Endpoints {
  /** Site root, e.g. "https://nullsink.is". The Anthropic SDK appends "/v1/messages". */
  site: string;
  /** OpenAI base, e.g. "https://nullsink.is/v1". The OpenAI SDK appends "/chat/completions". */
  openai: string;
  /** Balance endpoint, e.g. "https://nullsink.is/balance". */
  balance: string;
}

// Normalize an override to the site root: trim, drop trailing slashes, and tolerate a caller who
// passes the OpenAI base ("…/v1") by stripping a single trailing "/v1". Empty/absent => default.
export function resolveEndpoints(baseUrlOverride?: string | null): Endpoints {
  const raw = (baseUrlOverride ?? "").trim();
  let site = raw.length > 0 ? raw : NULLSINK_DEFAULT_BASE_URL;
  site = site.replace(/\/+$/, "").replace(/\/v1$/, "");
  return { site, openai: `${site}/v1`, balance: `${site}/balance` };
}

// The shape of src/models.json (generated by scripts/sync-models.ts). `input` is a plain string[]
// in JSON; toModelConfig narrows it to the ("text"|"image")[] pi wants.
export interface RawModel {
  id: string;
  name: string;
  reasoning: boolean;
  input: string[];
  cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
  contextWindow: number;
  maxTokens: number;
}
export interface ModelsFile {
  providers: { anthropic: RawModel[]; openai: RawModel[]; tinfoil: RawModel[] };
}

function toModelConfig(m: RawModel): ProviderModelConfig {
  const input = m.input.filter((x): x is "text" | "image" => x === "text" || x === "image");
  return {
    id: m.id,
    name: m.name,
    reasoning: m.reasoning,
    input: input.length > 0 ? input : ["text"],
    cost: m.cost,
    contextWindow: m.contextWindow,
    maxTokens: m.maxTokens,
  };
}

export interface NamedProvider {
  name: string;
  config: ProviderConfig;
}

// Build the three provider registrations. The apiKey is an env reference ("$NULLSINK_API_KEY") so
// pi resolves it per request and the raw key never lands in config/state. Compat is intentionally
// left to pi's auto-detection: a custom baseUrl that matches no known non-standard host yields
// exactly what nullsink + upstream need (max_completion_tokens, bearer auth, store:false).
export function buildProviders(models: ModelsFile, endpoints: Endpoints): NamedProvider[] {
  const apiKey = `$${API_KEY_ENV}`;
  return [
    {
      name: PROVIDER_IDS.anthropic,
      config: {
        name: "nullsink · Anthropic",
        baseUrl: endpoints.site,
        apiKey,
        api: "anthropic-messages",
        models: models.providers.anthropic.map(toModelConfig),
      },
    },
    {
      name: PROVIDER_IDS.openai,
      config: {
        name: "nullsink · OpenAI",
        baseUrl: endpoints.openai,
        apiKey,
        api: "openai-completions",
        models: models.providers.openai.map(toModelConfig),
      },
    },
    {
      name: PROVIDER_IDS.tinfoil,
      config: {
        name: "nullsink · Tinfoil",
        baseUrl: endpoints.openai,
        apiKey,
        api: "openai-completions",
        models: models.providers.tinfoil.map(toModelConfig),
      },
    },
  ];
}

// Fixed en-US currency formatting so output is stable regardless of the runtime locale.
const USD_FMT = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

export type BalanceKind = "ok" | "unknown" | "error";
export interface BalanceResult {
  kind: BalanceKind;
  balanceUsd?: number;
  message: string;
}

// Interpret a GET /balance response. 401 is deliberately ambiguous on nullsink's side (wrong key,
// or a right key whose deposit hasn't confirmed) — surface that rather than asserting "invalid".
export function interpretBalance(status: number, body: unknown): BalanceResult {
  if (status === 401) {
    return {
      kind: "unknown",
      message: "Key unknown or unfunded — wrong key, or a deposit that hasn't confirmed yet.",
    };
  }
  if (status < 200 || status >= 300) {
    return { kind: "error", message: `Balance check failed (HTTP ${status}).` };
  }
  const usd =
    body !== null && typeof body === "object" && "balance_usd" in body ? body.balance_usd : undefined;
  if (typeof usd !== "number" || !Number.isFinite(usd)) {
    return { kind: "error", message: "Malformed balance response from server." };
  }
  return { kind: "ok", balanceUsd: usd, message: `Balance: ${USD_FMT.format(usd)}` };
}

// --- persistent config + status rendering (pure) ----------------------------
// The store.ts I/O layer parses raw JSON through parseStoredConfig and renders through the helpers
// below; index.ts wires them to pi. Everything here is pure so the precedence + render matrix is
// unit-testable without a live runtime.

// Below this the statusline flags a low balance and nudges a top-up.
export const LOW_BALANCE_USD = 1;

// How the balance readout is surfaced. `both` shows the footer line AND the widget; `off` hides both.
export const DISPLAY_MODES = ["statusline", "widget", "both", "off"] as const;
export type DisplayMode = (typeof DISPLAY_MODES)[number];
export function isDisplayMode(x: unknown): x is DisplayMode {
  return typeof x === "string" && (DISPLAY_MODES as readonly string[]).includes(x);
}

// The on-disk shape of ~/.pi/agent/nullsink.json. Every field optional: a partial/older file still
// loads. `setupDone` gates the one-time first-run prompt (set even when the user skips, so it never nags).
export interface StoredConfig {
  apiKey?: string;
  baseUrl?: string;
  display?: DisplayMode;
  setupDone?: boolean;
}

// Coerce parsed JSON (unknown) into a StoredConfig, dropping any field with the wrong type or a blank
// string — a corrupt/hand-edited file degrades to defaults instead of throwing. Narrows with `in`/typeof
// (never an inline cast) so each read is actually checked.
export function parseStoredConfig(raw: unknown): StoredConfig {
  if (raw === null || typeof raw !== "object") return {};
  const out: StoredConfig = {};
  if ("apiKey" in raw && typeof raw.apiKey === "string" && raw.apiKey.trim()) out.apiKey = raw.apiKey.trim();
  if ("baseUrl" in raw && typeof raw.baseUrl === "string" && raw.baseUrl.trim()) out.baseUrl = raw.baseUrl.trim();
  if ("display" in raw && isDisplayMode(raw.display)) out.display = raw.display;
  if ("setupDone" in raw && raw.setupDone === true) out.setupDone = true;
  return out;
}

// Mask a key for display: keep the public "0sink_" prefix + last 4 chars, hide the 43-char secret
// middle. Short/odd values collapse to just the tail (or "…") so nothing sensitive leaks.
export function maskKey(key: string): string {
  const k = key.trim();
  if (k.length <= 4) return "…";
  if (k.length <= 10) return `…${k.slice(-4)}`;
  return `${k.slice(0, 6)}…${k.slice(-4)}`;
}

// Effective base URL string to feed resolveEndpoints: env override wins, then the saved file value,
// then undefined (resolveEndpoints applies the public default). Shared by startup, the config menu
// display, and the base-URL editor so all three agree on precedence.
export function resolveBaseUrlValue(envUrl?: string | null, fileUrl?: string | null): string | undefined {
  return envUrl?.trim() || fileUrl?.trim() || undefined;
}

// Snapshot the status renderers consume. `configured` = a key is present (env or saved); `balance` is
// the last /balance result (undefined until first fetch); `loading` = a fetch is in flight.
export interface StatusState {
  configured: boolean;
  loading: boolean;
  balance?: BalanceResult;
  keyMasked?: string;
}

// The single footer line. Order: no key → known balance (low vs ok) → 401 unfunded → error → mid-fetch
// → configured-but-not-yet-fetched. Always returns a string; the caller decides whether to show it.
export function renderStatusLine(s: StatusState): string {
  if (!s.configured) return "nullsink ○ no key · /nullsink setup";
  if (s.balance?.kind === "ok" && s.balance.balanceUsd !== undefined) {
    const amt = USD_FMT.format(s.balance.balanceUsd);
    return s.balance.balanceUsd < LOW_BALANCE_USD ? `nullsink ⚠ ${amt} · top up` : `nullsink ● ${amt}`;
  }
  if (s.balance?.kind === "unknown") return "nullsink ⚠ unfunded · top up";
  if (s.balance?.kind === "error") return "nullsink ⚠ balance unavailable";
  if (s.loading) return "nullsink … checking";
  return "nullsink ● key set";
}

// The two-line widget: the status line, then a key/action line. Reuses renderStatusLine so the two
// display modes never disagree on the headline.
export function renderWidget(s: StatusState): string[] {
  const second = s.configured
    ? `${s.keyMasked ?? "key set"} · /nullsink config`
    : "mint & fund at nullsink.is";
  return [renderStatusLine(s), second];
}
